name: 'arla_intel'
version: '1.0.0'
config-version: 2
profile: 'arla_intel'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  arla_intel:
    staging:
      +materialized: view
      +schema: dbt_staging
    marts:
      +materialized: table
      +schema: dbt_marts

